### ISSUE TITLE
Add powerpoint slides to the repo

### ISSUE THREAD

**Issue by IAmSahilVerma** [jonkrohn/ML-foundations#13]
Hi Jon,
I've been taking your course titled "Mathematical Foundations of Machine Learning" over at Udemy. I would like to suggest that we should add all the relevant PowerPoint slides to the repo to facilitate seamless learning experience. I'd especially helpful for revision purposes where someone would have to just go over a particular topic.

**Comment by jonkrohn** [comment]
Hi Sahil! 

All of the slides are available at [jonkrohn.com/talks](https://www.jonkrohn.com/talks). Simply us the "Find" functionality in your browser of choice to locate the "linear algebra" or "calculus" (or whatever subject you're looking for on that page) slides.

Best,
Jon

**Comment by IAmSahilVerma** [comment]
Jon,

Thank you for point out the resource material. Greatly appreciate it.

Regards,
Sahil
