### ISSUE TITLE
dummy: ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).

### ISSUE THREAD

**Issue by yuriy-babenko** [jonkrohn/ML-foundations#14]
https://github.com/jonkrohn/ML-foundations/blob/f6e244f64dd9b93ce63aa67a2a3a2f3ed5f6dc61/notebooks/6-statistics.ipynb#L8074

Hitting "ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data)." with provided code. 

Per [pandas](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html), seems that dummy creates a default bool if no dtypes is provided. [OLS](https://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.OLS.html#statsmodels.regression.linear_model.OLS) does not support mixed data types. 

Fix: adding dtype into the dummy solves the problem for me: 

`dummy = pd.get_dummies(iris.species, dtype = 'int64')`

**Comment by jonkrohn** [comment]
Thank you, @yuriy-babenko! ...both for noting this library-version-related error and for coming up with a simple solution. I'm updating the notebook presently and will commit the code today-ish.
