### ISSUE TITLE
Adelie penguins on Dream Island: answer is not correct

### ISSUE THREAD

**Issue by horvatha** [jonkrohn/ML-foundations#3]
In [6-statistics.ipynb](https://github.com/jonkrohn/ML-foundations/blob/master/notebooks/6-statistics.ipynb)
the result of Dream Island Adélie question isn't correct. At In[133]  f and m contains all the Adélie penguins, not just the once on  Dream Island. The correct answer is t=-2.43, p=0.0179.

(In[137]:  tp.pvalue is nicer than tp[1] )

**Comment by jonkrohn** [comment]
Thanks, @horvatha! I haven't had a chance to dig into this yet, but I suspect you're right and will resolve the issue shortly if so. All my best over the weekend :)

**Comment by jonkrohn** [comment]
Yup, you were correct, @horvatha! Thank you for finding this error, which I fixed one moment ago :)
