### ISSUE TITLE
wrong reference to eigenvectors instead of eigenvalues

### ISSUE THREAD

**Issue by eavelardev** [jonkrohn/ML-foundations#4]
line 5709 of [2-linear-algebra-ii.ipynb](https://github.com/jonkrohn/ML-foundations/blame/master/notebooks/2-linear-algebra-ii.ipynb)
"* Non-zero singular values of $A$ = square roots of ~~eigenvectors~~ eigenvalues of $AA^T$ = square roots of ~~eigenvectors~~ eigenvalues of $A^TA$\n"

**Comment by jonkrohn** [comment]
Great catch, @eavelardev – thanks! Now fixed :)
